### ISSUE TITLE
geoh5py.objects.drillhole.Drillhole.locations dtype inconsistency

### ISSUE THREAD

**Issue by markgrujic** [MiraGeoscience/geoh5py#117]
**Summary:**
The calculated survey locations are not consistent with those calculated elsewhere, e.g. in Geoscience Analyst.

**Expected behaviour:**
Survey location at depth=0 should equal the collar location

**Actual behaviour:**
It's not - there's a shift.

**Code that seems to fix it:**
Convert the data type of the deviation calculation to float64 to match the collar dtype.
This seems to fix things, but I'm not sure if it breaks others so probably better reporting here instead of a PR?
```
    def locations(self):
        """
        :obj:`numpy.ndarray`: Lookup array of the well path x,y,z coordinates.
        """
        if (
            getattr(self, "_locations", None) is None
            and self.collar is not None
            and self.surveys is not None
        ):
            lengths = self.surveys["Depth"][1:] - self.surveys["Depth"][:-1]
            self._locations = np.c_[
                self.collar["x"] + np.cumsum(np.r_[0.0, lengths * self.deviation_x]).astype('float64'),
                self.collar["y"] + np.cumsum(np.r_[0.0, lengths * self.deviation_y]).astype('float64'),
                self.collar["z"] + np.cumsum(np.r_[0.0, lengths * self.deviation_z]).astype('float64'),
            ]

        return self._locations
```

**Comment by domfournier** [comment]
@markgrujic Thanks Mark for this. Just getting back from vaca. 
If you want to create the PR with your fix that would be great - pytest will tell us if it conflicts, but I don't see why not.

**Comment by markgrujic** [comment]
Done, hope you had a good break!
