### ISSUE TITLE
Segy?

### ISSUE THREAD

**Issue by RichardScottOZ** [MiraGeoscience/geoh5py#151]
I was talking to some gentlemen of the seismic persuasion last week and I note the new Analyst version has 2D segy capability. Is this on the roadmap?

Apologies if I missed it as you are all crazy productive and literally cannot look at all the updates.

**Comment by domfournier** [comment]
@RichardScottOZ Most definitely. We can bump it up on the priority list.

**Comment by RichardScottOZ** [comment]
Thanks very much!

**Comment by domfournier** [comment]
Will let GA deal with that part.
