### ISSUE TITLE
Support for textured surfaces

### ISSUE THREAD

**Issue by geolehmann** [MiraGeoscience/geoh5py#161]
I am using the GEOH5 format in a project to visualize photogrammetry scans from underground mines together with surronding drillholes (in this project, I do not use the geoh5py library but read and write .geoh5 files via a HDF5 parser (hdf5-rs, for Rust)). 

The photogrammetry scans come as meshes in the Wavefront .obj format together with textures (jpeg etc.), and I store the mesh together with the texture in the .geoh5 format. Now I want to make this format as compatible as possible with Geoscience ANALYST, although the Analyst doesnt support textured surfaces yet (I am aware the documentation states that unsupported additional data types are omitted by the ANALYST). 

So, do you have any suggestions for a suitable structure? I don´t know if textured surfaces are already planned for future releases of the ANALYST, but maybe you already have a specification how to store them in the GEOH5 format. 

My current implementation is to modify the `GeoImage` object and add a separate 2D dataset named "UV" besides the current Cells/Data/Type/Vertices Datasets/Groups where I store the uv coordinates of the texture.

**Comment by domfournier** [comment]
@sebhmg : Thoughts?

**Comment by geolehmann** [comment]
Do you have any updates on this? Otherwise I would stick with my current implementation of the UV dataset and close this issue.

**Comment by sebhmg** [comment]
Hello @geolehmann,
I highly appreciate that you are asking for our advice before introducing new data within a geoh5 file.
After discussions between @domfournier, @jincandescent and myself, we believe the way this new data is saved is not critical for now. When Geoscience ANALYST does support this concept of textured surface, it will be possible to reprocess your custom geoh5 files with some script, and makes them compliant with the format expected by the software.

Meanwhile, we recommend storing the data under existing supported structures: note that Analyst will no save unrecognized data back to disk.
You could for example store U and V as surface property datasets, and use JSON under the metadata dataset to link together the U, V and the image:
```json
{
  "textures": [
     {
       "image": "<the geoimage UUID>",
       "U": "<the U property UUID>",
       "V": "<the V property UUID>"
     }
  ]
}
```

Does it make sense?
Let us know if you have further questions !

**Comment by geolehmann** [comment]
Hi, many thanks for the suggestion and the explanation, the JSON approach seems fine to me. This way I could also better support multiple textures per mesh. I´ll close this issue.
