### ISSUE TITLE
drillholes FROM-TO conversion issue

### ISSUE THREAD

**Issue by MatthieuCMira** [MiraGeoscience/geoh5py#224]
I used some drillholes data imported from Analyst 4.1. (in a drillholes group I did not created)
They have FROM(1) TO(1) parameters in a new interval.
When I imported them in python, the '.0' character from the original FROM and TO were converted to '' in the FROM(1) TO(1).
ex: 186.03 => 1863 

I did not have this issue playing with geoh5py drillholes objects in python and importing them in analyst. Thus it might come from some manipulation in analyst

**Comment by domfournier** [comment]
Could not reproduce.
