### ISSUE TITLE
group uuid does not work with uijson

### ISSUE THREAD

**Issue by MatthieuCMira** [MiraGeoscience/geoh5py#225]
I tried to open a drillholes group (uuid:825424FB-C2C6-4FEA-9F2B-6CD00023D393) using uijson.

` "drillholes": {
  "label": "drillholes group to match",
  "main": true,
  "meshType": [
   "{825424FB-C2C6-4FEA-9F2B-6CD00023D393}"
  ],
  "value": "",
  "enabled": true
 },`
 
 However, the groups are not recognize when I open the uijson in analyst.

**Comment by domfournier** [comment]
Will be address by the GA team on GA-6618
