### ISSUE TITLE
Create constants for the object UUIDs

### ISSUE THREAD

**Issue by donos90** [MiraGeoscience/geoh5py#227]
Suggestion to improve the API by making the UUID's for object types into constants.

e.g. for the code snippet:

`    drillholes = ws.get_entity('{7CAEBF0E-D16E-11E3-BC69-E4632694AA37}')
 `

the user would use constant:
`    drillholes = ws.get_entity(geoh5py.DRILLHOLE)
 `

**Comment by domfournier** [comment]
Hmm because you would like to get all objects of a type? Currently `get_entity` targets a specific entity, not an entity_type.

**Comment by donos90** [comment]
My mistake. I was thinking more for the ui.json component. You've since showed me how to select objects using isinstance.
