### ISSUE TITLE
.add_data() to geoh5py object - bug

### ISSUE THREAD

**Issue by MatthieuCMira** [MiraGeoscience/geoh5py#232]
I tried to push an object to a drillhole using 
`drillhole.add_data(matched)`

But, as my object (from analyst) has no parent.property_group_ids it raises the following error:
```
File "D:\git\geoh5py\geoh5py\objects\drillhole.py", line 482, in validate_depth_data
    ind = len(self.parent.property_group_ids)
TypeError: object of type 'NoneType' has no len()
```
Is it possible to catch this error please? Thanks

**Comment by domfournier** [comment]
Will be tackled by GEOPY-598
