### ISSUE TITLE
Create GEOH5 Standard Repo

### ISSUE THREAD

**Issue by ngodber** [MiraGeoscience/geoh5py#255]
Hey Dom,

It would be good to formally have a repository to hold the GEOH5 standard that isn't co-hosted within the Geoh5py implementation of said standard. I was searching for formal documentation but couldn't find anything beyond what was on the readthedocs for GeoH5py and https://gist.github.com/jincandescent/06a3bd4e0e54360ad191. 

Thoughts?

**Comment by domfournier** [comment]
Hi @ngodber , sorry didn't see this one. We put it all here: https://geoh5py.readthedocs.io/en/stable/content/geoh5_format/index.html

It is technically under geoh5py, but specific to geoh5 format.
Do you have something else in mind?

**Comment by ngodber** [comment]
No worries - I think this was lodged before that existed. As there is functionally only a single implementation it doesn't matter. In future it would be good, particularly if the standard evolves and there is more than one implementation, to have it hosted in its own repo and be version controlled.
