### ISSUE TITLE
missing cells from Drillhole object

### ISSUE THREAD

**Issue by cardinalgeo** [MiraGeoscience/geoh5py#276]
Hello again! It's unclear if this deserves "Issue" status (I may just be misunderstanding something) but I'll outline the problem below nonetheless. 

### Environment data
OS (Windows | Mac | Linux distro) and version: Darwin arm64 21.3.0
Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
python version: 3.9.13
geoh5py version: 0.4.0

### Expected behavior
After adding interval data to a `Drillhole` object, I expect vertices and cells to be computed and made accessible. 

### Actual behavior
Instead, it appears that neither are computed, as seen in the MRE below. This is surprising as, upon adding data via `add_data()`, the data are seemingly validated using `validate_interval_data`, at which point it appears that desurveying occurs and cells and vertices are created (e.g., [here](https://github.com/MiraGeoscience/geoh5py/blob/develop/geoh5py/objects/drillhole.py#L479) and [here](https://github.com/MiraGeoscience/geoh5py/blob/develop/geoh5py/objects/drillhole.py#L530-L535)). 

### Steps to reproduce
```
from geoh5py.workspace import Workspace
from geoh5py.groups import DrillholeGroup
from geoh5py.objects import Drillhole
import numpy as np

workspace = Workspace("../bug_mre.geoh5")

dh_group = DrillholeGroup.create(workspace)

# Create a simple well
total_depth = 100
dist = np.linspace(0, total_depth, 10)
azm = np.ones_like(dist) * 45.
dip = np.linspace(-89, -75, dist.shape[0])
collar = np.r_[0., 10., 10]

# data intervals
from_to = np.vstack([
    [0.25, 25.5],
    [30.1, 55.5],
    [56.5, 80.2]
])

# create drillhole
well = Drillhole.create(
    workspace, collar=collar, surveys=np.c_[dist, azm, dip], name="Drillhole", parent=dh_group
)

well.add_data({
    "random_values": {
        "values": np.array([1, 1, 1],dtype="float64"),
        "from-to": from_to,
    }
})

# inspect drillhole
print(f"Interval data are {well.get_data('random_values')[0].values}")
print(f"Cells are {well.cells}")
print(f"Vertices are {well.vertices}")


workspace.close()
```

**Comment by domfournier** [comment]
Hi @cardinalgeo , good observation but this is expected as of v0.4.0. Drillhole objects got a big revamp and are now Concatenated entities

![image](https://user-images.githubusercontent.com/55204635/206785734-a4fd3222-9ee9-4c43-bada-0ecf850cc28d.png)

Vertices and cells are never stored, only the collar and surveys. The data locations are stored in tables defined by the FROM, TO and DEPTH locations. Those are stored under `property_groups` that group all data with the same intervals. You can access them like this:

```
workspace.open()
data = well.get_data("random_values")[0]
print(data.values, data.property_group.from_.values, data.property_group.to_.values, )
workspace.close()
```

**Comment by cardinalgeo** [comment]
Got it, thanks @domfournier! If the cells/vertices are not stored, does this mean that Geoscience Analyst computes them on the fly from the collar + survey + interval data supplied by the geoh5 file?

**Comment by domfournier** [comment]
That is it yes.
