### ISSUE TITLE
error when add_data with different shape

### ISSUE THREAD

**Issue by MatthieuCMira** [MiraGeoscience/geoh5py#339]
Error when add_data to surface. 
[reproduce_error.zip](https://github.com/MiraGeoscience/geoh5py/files/11366567/reproduce_error.zip)

**Comment by domfournier** [comment]
Need to use the `.create` method. 
![image](https://user-images.githubusercontent.com/55204635/236932582-3f7c701a-016b-4ce8-9a4b-1f234cfce853.png)

That being said, we could/should allow to just instantiate the class instead of calling `create`
