### ISSUE TITLE
Python 3.6.X not supported with pip install

### ISSUE THREAD

**Issue by maxshowarth** [MiraGeoscience/geoh5py#48]
Documentation indicates that Python 3.6 or higher is supported but requirements on PyPi indicate 3.7+ is required.

See the following error message:

``https://pypi.org:443 "GET /simple/geoh5py/ HTTP/1.1" 304 0
  Link requires a different Python (3.6.9 not in: '>=3.7,<4.0')``

Could someone confirm whether Python 3.6.9 is still supported?

**Comment by domfournier** [comment]
@maxshowarth, I just tested locally and can confirm that 3.6 is no longer supported. The lowest I have managed to go was 3.7

![image](https://user-images.githubusercontent.com/55204635/112091379-77e4e200-8b52-11eb-8315-1437ba4d5915.png)

I will update the docs to reflect the change. 

Sorry about the confusion and I hope you can move to >=3.7 without too much trouble.

**Comment by maxshowarth** [comment]
Thank you! I am working on updating our environment now.
