### ISSUE TITLE
Live updates to geoh5 file in anaylst

### ISSUE THREAD

**Issue by maxshowarth** [MiraGeoscience/geoh5py#96]
Hello,

I wanted to ask if there is a plan to implement a "live update" feature so that changes made to an open geoh5 file are reflected in Analyst immediately?

We would like our users to be able to do some processing in a Jupyter notebook, and write that data directly back to the geoh5 file. Currently, users have to re-open the file in Analyst since there doesn't seem to be a "refresh" button anywhere and the changes are not automatically updated.

Apologies if this is not the correct forum to ask this question.

**Comment by domfournier** [comment]
Hi @maxshowarth 
Great question. The feature already exists, but it is only available to Pro (licensed) users. This is sort of where the freeware ends, and the paid "perks" start.  GA uses a monitoring folder to load right away any geoh5 file that is being copied over. So we can get python to drop small files with just the modified object or data, and GA loads it up on it's own and show it to you. It looks something like this... 

![live_like_demo](https://user-images.githubusercontent.com/55204635/120240364-3721dd00-c215-11eb-814b-564c9e4e69c6.gif)

Here is a notebook with an example if you join Pro ;)


[live_update_demo.ipynb.zip](https://github.com/MiraGeoscience/geoh5py/files/6572137/live_update_demo.ipynb.zip)
(sorry had to zip for github)

**Comment by domfournier** [comment]
For reference @glennp72: I think we were starting to work on similar features.
